name: Shop
description: Make shop chests
author: StarTux
version: 0.1
api-version: 1.13
main: com.winthier.shop.ShopPlugin
website: https://cavetale.com
depend: [SQL, GenericEvents]
softdepend: []
commands:
  market:
    description: Warp to the market
    usage: /<command>
    permission: shop.market
  shop:
    description: Shop user interface
    usage: /<command>
    permission: shop.shop
  shopadmin:
    description: Admin interface
    usage: |-
      /<command> reload - Reload configs
      /<command> plotinfo - Display current plot info
      /<command> makeplot - Make plot from selection
      /<command> deleteplot - Delete current plot
      /<command> showplots - Highlight nearby plots
      /<command> transfer - Transfer plot
    permission: shop.admin
permissions:
  shop.shop:
    description: Use /shop
    default: op
  shop.create:
    description: Create your own shops
    default: op
  shop.market:
    description: Visit the market via /market
    default: op
  shop.market.claim:
    description: Claim a plot on the market
    default: op
  shop.market.override:
    description: Override market plot restrictions
    default: op
  shop.admin:
    description: Use /shopadmin
    default: op
